### ISSUE TITLE
Refactor: Update OAuth scopes to remove Google Books API

### ISSUE THREAD

**Issue by codingcodymiller** [codingcodymiller/requote#33]
## ✅ Task List

> ##### Check list items that need to be done in order to complete the refactor.

- [ ] ... 
- [ ] ...
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.

**Comment by codingcodymiller** [comment]
This actually needs to be kept in order to try and get the best resolution possible for each book cover
