### ISSUE TITLE
Polish: Update endpoint to save book image to seek cover images from all possible locations, and save the largest one

### ISSUE THREAD

**Issue by codingcodymiller** [codingcodymiller/requote#38]
## ✅ Task List

- [ ] Update endpoint to save a book to do the following:
  - [ ] Check the dimensions of the image to see if the innate width is above 300px (use [image-size](https://www.npmjs.com/package/image-size) package, relatively small import cost). 
    - [ ] If so, save using the default image path from ISBNdb
    - [ ] If not, start a background search for all possible images of the cover from Google Books, New York Times, etc. Once all images have been received, determine the largest image  and update the book listing in the database to use the largest image as its book cover
- [ ] Maybe update to store in S3 to avoid images being deleted in the future.
