### ISSUE TITLE
Feature 4: User can sort quotes

### ISSUE THREAD

**Issue by codingcodymiller** [codingcodymiller/requote#4]
## ⚙️ Feature

User can sort quotes in quote list by date created, page number, or quote length.

## 📐 Functionality

User can choose a type of sort (Date Added is default), and can also invert direction of sort.

### Mobile

![image](https://user-images.githubusercontent.com/32880187/149827583-b885f418-c81c-4137-a2b1-abc280936dbc.png)

### Desktop

![image](https://user-images.githubusercontent.com/32880187/149827971-7030c0db-33e9-4799-b990-d76251e6beab.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update endpoint to get quotes in creation order
  - [x] Use a parameter to determine ascending or descending
  - [x] utilize template literal to inject sort order into query
- [x] Create an endpoint to get quotes in order of page number
  - [x] Use a parameter to determine ascending or descending
  - [x] utilize template literal to inject sort order into query
- [x] Create an endpoint to get quotes in order of quote length
  - [x] Use a parameter to determine ascending or descending
  - [x] utilize template literal to inject sort order into query
- [x] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [x] Update QuoteDashboard to encapsulate the search bar, sort controls, and quote list
  - [x] `sortType` (default `"date"`)
  - [x] `isReversed` (default `false`)
  - [x] method `getQuotes`
    - [x] Format query based on current values for sort and display direction in Context
  - [x] method `updateSortType`
    - [x] Update context value for `sortType` or `isReversed`
- [x] Create a component for quote sorting
  - [x] Include a modal for selecting the sort order

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
