### ISSUE TITLE
Feature: User can edit quotes

### ISSUE THREAD

**Issue by codingcodymiller** [codingcodymiller/requote#45]
## ⚙️ Feature

Users will be able to edit existing quotes.

## 📐 Functionality

Users can click on an icon on each quote in their quote list to be redirected to the SaveQuoteForm again with the existing values for the quote already filled in.

## ✅ Task List

- [x] shift all ids to UUID
- [x] Create a new PATCH endpoint to edit an existing quote.
  - [ ] front end will need to send quote id with data.
  - [x] may require adjusting data sent in quotes endpoint to include id.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Adjust QuoteListItem to include an edit icon
  - [x] add a click event listener to redirect to the edit page
- [x] create EditPage, which uses SaveQuoteForm but with values provided as props.
  - [x] will need to send quote id with data to the back-end
  - [x] sends a request to the edit endpoint
  - [x] redirect to quote list
    - [x] scroll to quote on redirect
    - [x] create an id on each quote, which is their UUID

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented-out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
