### ISSUE TITLE
Feature: User can delete quotes

### ISSUE THREAD

**Issue by codingcodymiller** [codingcodymiller/requote#46]
## ⚙️ Feature

Users will be able to delete quotes they have created.

## 📐 Functionality

A delete icon will be added to each quote. When the delete icon is clicked, a menu will with an X and checkmark icon to either confirm or cancel.

## ✅ Task List

- [x] Update `schema.sql` to include `isDeleted` for each quote.
  - [x] Its value will be a Boolean

### ☁️ Server

- [x] Update `server/index.js` to include a PATCH endpoint for deletion
  - [x] front end will send quote id
  - [x] update the quote's row in the database to have the `isDeleted` column set to `true`
  - [x] send 204 response ("No Content") to inform the front end that deletion was successful.
- [x] Update GET endpoint to get all quotes to only select quotes from the database where `isDeleted` is `false`
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update QuoteListItem component to include a delete icon
  - [x] When clicked, it should open a slide menu from the side with a red X icon and a green checkmark icon to either confirm or cancel quote deletion
    - [x] Clicking the cancel icon closes the menu
    - [x] Clicking the delete icon again while the menu is open closes the menu
    - [x] clicking the checkmark sends a PATCH request to the delete endpoint.
    - [x] ensure that the list is updated when a successful delete 204 response is received.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
