### ISSUE TITLE
Feature 3: User can filter quotes by search term

### ISSUE THREAD

**Issue by codingcodymiller** [codingcodymiller/requote#5]
## ⚙️ Feature

User can type in a search term to see only quotes containing that search term in the quote body.

## 📐 Functionality

User will type into a search bar and the quote list will live update will quotes that match the search term.

### Mobile

![image](https://user-images.githubusercontent.com/32880187/149829030-61e498c5-a6cc-4b8c-b29f-a591aea95909.png)

### Desktop

![image](https://user-images.githubusercontent.com/32880187/149828989-296b428a-fe31-4292-9e43-fc5c50a96b0b.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Create an endpoint to search for term in quotes
  - [x] Use [Full Text Search](https://www.compose.com/articles/mastering-postgresql-tools-full-text-search-and-phrase-search/)
- [x] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [ ] Update QuoteDashboard component that will encapsulate the search bar and quote list
  - [x] `searchTerm` (default `null`)
  - [x] create method `searchQuotes`
    - [x] Send request to get all quotes that match search term, then update quote list
- [x] Create a component for the quote search bar
  - [x] `quoteSearch`
    - [x] Debounce before request is sent
    - [x] Component is passed callback as prop (`searchQuotes`)

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
