### ISSUE TITLE
Feature 6: User can transcribe quote from image using OCR

### ISSUE THREAD

**Issue by codingcodymiller** [codingcodymiller/requote#6]
## ⚙️ Feature

User will be able to upload an image and transcribe the text from it in order to save the quote.

## 📐 Functionality

User can upload an image by either clicking on the image upload area or drag and drop the image onto the page, then the image will be interpreted and any text in it will be auto-inserted into the quote field in the form to save a quote.

### Mobile

![image](https://user-images.githubusercontent.com/32880187/149830687-e3e86792-44a6-45ea-ae0d-88b838c0d835.png)

### Desktop

![image](https://user-images.githubusercontent.com/32880187/149830838-d4366122-ff3a-4edb-a8ba-531b87554728.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Create a component to act as a file dropzone using `react-dropzone`
- [x] Update component to save a quote to include dropzone component
- [x] Have files dropped in dropzone send files to tessaract.js to get text
- [x] Save text returned from tesseract.js as new state for textarea component

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
