### ISSUE TITLE
Feature 7: User can view details of a single book

### ISSUE THREAD

**Issue by codingcodymiller** [codingcodymiller/requote#7]
## ⚙️ Feature

User will be able to view a detail view for a single book to verify if it is the book they want to save a quote for.

## 📐 Functionality

While searching for books, a user will be able to click an "ⓘ" icon to see details for that book. They can also return to the search they had in progress from that page.

### Mobile

![image](https://user-images.githubusercontent.com/32880187/149831427-4d0ab601-6555-4f8d-8217-fa0f5c2d52e1.png)

### Desktop

![image](https://user-images.githubusercontent.com/32880187/149831472-9d250a13-376d-4f52-894f-df98eb0bc701.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Create an endpoint to get details for a single book
 - [x] Check if the book already exists in the database
   - [x] If so, get book details and send them as a response
   - [x] If not, get book details from ISBNdb and send them as a response
- [x] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a BookDetails component to show the details of a single book
  - [x] Add a back button to show the previous view using React Router
  - [x] Create a function named `sanitizeSynopsis` to sanitize synopsis using [DOMPurify](https://www.npmjs.com/package/dompurify) and return object with `__html` property holding that sanitized value
  - [x] Assign sanitized content using [`dangerouslySetInnerHTML`](https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml) React prop
  - [x] Ensure that it matches the Figma
- [x] Update BookListItem component to include information icon to navigate to book details view
- [x] Update BookCover component to include information icon to navigate to book details view

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
